TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += Mezflipr_single.db
DB += Mezflipr_common.db
DATA += Mezflipr.proto

#=======================================
include $(TOP)/configure/RULES
