TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += Mezflipr_single_v1.db
DB += Mezflipr_common_v1.db
DATA += Mezflipr_v1.proto
DB += Mezflipr_single_v2.db
DB += Mezflipr_common_v2.db
DATA += Mezflipr_v2.proto

#=======================================
include $(TOP)/configure/RULES
