TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += Mezflipr.db
DATA += Mezflipr.proto

#=======================================
include $(TOP)/configure/RULES
